### PR TITLE
full data file and extra for titlepage 

### PR DESCRIPTION
**Pull request by rachelaronoff**
As discussed, Included full data csv file from double check into new folder under data 
/full_data_csv/ to get back to correct 2020 data.  Also commit for small edits in titlepage, to get rid of broken Biodesign link and add the Zenodo archive of image data. 
Thanks in advance for integrating these info.

### CODE REVIEW

**Comment by rachelaronoff** [comment]
additionally, in addition to the integration needed from the big file, the team still needs to make a Zenodo archive with the image data of the scored microbio cards for the '22/'23 campaigns.

**Review by hammerdirt-analyst — APPROVED** [review]
will integrate the new data file on a separate branch

**Comment by rachelaronoff** [comment]
does this mean this link etc will be updated still?
https://hammerdirt-analyst.github.io/qualite-deau/titlepage.html
greetings from Basel...

**Comment by hammerdirt-analyst** [comment]
Non, this means you added new data, we need to verify that it is correct. Nothing else changes. Please do not put photos. Those questions should be decided before you make a pull request.

**Pull request merged**
